variables:
  loghub_root: /tmp/loghub
root:
  parser:
    name: DefaultLogParser
    params:
      pattern: (?P<content>.*?)
  path: /
loggers:
  - name: apache
    path: '{loghub_root}/Apache'
    modules:
      - apache
    template: apache
  - name: proxifier
    path: '{loghub_root}/Proxifier'
    modules:
      - proxifier
    template: proxifier



